toc:
    - name: Main Modules
      children:
          - name: DerivAPI
          - name: DerivAPIBasic
    - name: Abstract Objects
      children:
          - name: Immutables
            description: |
                Abstract objects that provide static content and methods to make
                use of them, changing internal fields of these objects is blocked
                and they do not receive updates.
            children:
                - name: Account
                - name: Assets
                - name: Underlying
                - name: Tick
                - name: Candle
                - name: Transaction
                - name: ContractGroup
                - name: Buy
                - name: Sell
          - name: Streams
            description: |
                Live stream of data, plus some dynamically updated fields, you
                can subscribe to changes using the `onUpdate` method on all of
                these classes.
            children:
                - name: Balance
                - name: CandleStream
                - name: Contract
                - name: TickStream
                - name: TransactionStream
          - name: Types
            description: |
                Container classes for data types, providing means to convert them
                to other types and represent them to the UI. These are mostly
                simpler objects used for representing data.
            children:
                - name: MarketValue
                - name: Monetary
                - name: FullName
                - name: CustomDate
                - name: DateRange
                - name: Duration
                - name: DurationRange
                - name: Immutable
                - name: Stream
    - name: Core Functionality
      children:
          - name: Cache
          - name: SubscriptionManager
          - name: Storage
    - name: Object References
      description: |
          These are plain JavaScript objects that are named to easily refer to
          them in this documentation, they don't physically exist as a class
          in this codebase.
      children:
          - name: Parameters
            children:
                - name: CandlesParam
                - name: TicksParam
                - name: ContractsParam
                - name: BuyParam
                - name: SellParam
                - name: HistoryRange
          - name: Plain objects (returned from methods)
            children:
                - name: SpotDurations
                - name: ForwardDurations
                - name: Durations
                - name: DurationUnits
